sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '4'
before_install:
- npm i -g npm@^2.0.0
before_script:
- npm prune
after_success:
- npm run semantic-release
branches:
  only:
  - master
deploy:
  provider: npm
  on:
    branch: master
  api_key:
    secure: G/BZxzINabvOvI9XEHV0oOHRedOsFl3DWBJp4m1SwuBjI1QJE/NsBkMH+rjbkz4CNObK5M6L6CuzyxsJAu2JM4wTpcPQid2FkUVVSBQyISWBEQaZ9XT8FJ7WvuQzxQTywSi2uZ81fSytpSd+devPuKC2hL1TdSGWjrycwwY8Ai910L5PN3Qp7puYyHLrO73vLcXpmE+1sY5+E7Ekfk7WYIivrWlzVFfKJbaPAgQUVZJC8kRVl2gdIRTX35tZDyxdaAVba0CvWxXICs1U0j035uKbJgYX0FdPRlfDim0wAQC9Q1ahNTcec1s3qcj3TKYxqD4T3oI6bD06+3by3jyzlM2dCyJpk1nmGVnZAnMO6Y7TOK6KbCmYy62duH0DbnElnUdT3c8xAJm7UPdIV2M35CCvWn0ZruXqc0YilQk0zSeqnBjINipenvmBGLr5+Osbv8TvKDp35Y3lN6sYVLDy8JwW2r+PL/5iQY+OVkFz3zDMZkw9NCS63XTruPe3gT5yX7D10h8xbBApriycehPoXIWbVH6Jgw8d2DQEyJQbsgMRxIWReENb34AqHzy/f2bywgdKOnVInnWPU8HIj2Gi6v30OGaw6sBFiaO7OGOAYAe1bG5S4nkJU3dXjiWaE1UHR+M5Q2V2QfjbMc/gUbiutzfC74YGiDYoUubPtBFpmH0=
